name: Build

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 7.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Build & Pack
        run: dotnet pack -c Release -o ./artifacts VkNet.AudioBypassService/VkNet.AudioBypassService.csproj

      - name: Publish
        run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
