name: Build

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET 6.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Publish
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: VkNet.AudioBypassService/VkNet.AudioBypassService.csproj
          NUGET_KEY: ${{secrets.NUGET_TOKEN}}
